version: "3.8"
services:
  app: 
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: url_shortener:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      # - redis
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: djheroku
    volumes:
      - pgdata:/var/lib/postgresql/data/

  # redis:
  #   image: redis:latest

volumes:
  pgdata: