version: "3.8"
services:
  app: 
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: url_shortener:django
    container_name: django_container
    command: /bin/sh -c "while sleep 1000; do :; done"
    # python manage.py runserver 0.0.0.0:8000